In [3]:
import os
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [4]:
df_avito = pd.read_csv("Silver/apparts_vente.csv")

In [5]:
#### AVITO RAW DATA INFO
df_avito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41571 entries, 0 to 41570
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   description             41570 non-null  object
 1   Frais de syndic / mois  18762 non-null  object
 2   price                   32898 non-null  object
 3   Meublé                  0 non-null      float64
 4   Chauffage               0 non-null      float64
 5   title                   41571 non-null  object
 6   Concierge               0 non-null      float64
 7   category                0 non-null      float64
 8   price_value             32898 non-null  float64
 9   Standing                28100 non-null  object
 10  Disponibilité           28405 non-null  object
 11  Surface totale          32113 non-null  object
 12  Âge du bien             29261 non-null  object
 13  Sécurité                0 non-null      float64
 14  area                    0 non-null      float64
 15  Surface habitable       41038 non-null  object
 16  list_time               41571 non-null  object
 17  city                    41571 non-null  object
 18  seller_name             41564 non-null  object
 19  Chambres                40997 non-null  float64
 20  Terrasse                0 non-null      float64
 21  Cuisine équipée         0 non-null      float64
 22  Condition               31721 non-null  object
 23  Balcon                  0 non-null      float64
 24  seller_phone            38748 non-null  float64
 25  image_count             41571 non-null  int64
 26  Parking                 0 non-null      float64
 27  Salons                  37725 non-null  float64
 28  Salle de bain           40041 non-null  float64
 29  Climatisation           0 non-null      float64
 30  Type d'appartement      5656 non-null   object
 31  Ascenseur               0 non-null      float64
 32  Étage                   40641 non-null  float64
 33  seller_type             10618 non-null  object
 34  url                     41571 non-null  object
 35  image_url               38246 non-null  object
dtypes: float64(18), int64(1), object(17)
memory usage: 11.4+ MB

In [6]:
df_avito = df_avito.drop(
    columns=[
        # all-empty columns (0 non-null)
        'Meublé', 'Chauffage', 'Concierge', 'category', 'Sécurité',
        'Terrasse', 'Cuisine équipée', 'Balcon', 'Parking',
        'Climatisation', 'Ascenseur',

        # mubwab-only / metadata (drop to align with avito)
        'Frais de syndic / mois', 'Disponibilité', 'Standing', 'Surface totale',
        'Âge du bien', 'seller_name', 'seller_phone', 'image_count', 'Salons',
        'Étage', "Type d'appartement", 'seller_type', 'image_url'
    ]
)

In [7]:
df_avito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41571 entries, 0 to 41570
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   description        41570 non-null  object
 1   price              32898 non-null  object
 2   title              41571 non-null  object
 3   price_value        32898 non-null  float64
 4   area               0 non-null      float64
 5   Surface habitable  41038 non-null  object
 6   list_time          41571 non-null  object
 7   city               41571 non-null  object
 8   Chambres           40997 non-null  float64
 9   Condition          31721 non-null  object
 10  Salle de bain      40041 non-null  float64
 11  url                41571 non-null  object
dtypes: float64(4), object(8)
memory usage: 3.8+ MB

In [8]:
df_avito

,description,price,title,price_value,area,Surface habitable,list_time,city,Chambres,Condition,Salle de bain,url
0,"Situé à Mohammedia, le projet résidentiel ODYS...",495000 DH,ODYSSÉE – Studios & Appartements haut standing,495000.0,NaN,38 m²,2026-05-31T11:18:22Z,Mohammedia,1.0,Neuf,0.0,https://www.avito.ma/fr/centre_ville/apparteme...
1,فرصة رائعة لشراء شقة في بير الرامي، القنيطرة. ...,770000 DH,À vendre – Appartement haut standing à Bir Rami,770000.0,NaN,85 m²,2026-05-26T11:54:21Z,Kénitra,2.0,Bon état,2.0,https://www.avito.ma/fr/bir_rami/appartements/...
2,"Studio meublé à vendre – Oasis, Casablanca 📍 ...",1250000 DH,STUDIO à vendre meublé 56 m² avec piscine à Oasis,1250000.0,NaN,52 m²,2026-05-24T20:58:31Z,Casablanca,1.0,Bon état,1.0,https://www.avito.ma/fr/oasis/appartements/STU...
3,Appartement à vendre à El Jadida El Ghorba prè...,430000 DH,Appartement à vendre avec apport,430000.0,NaN,62 m²,2026-05-27T05:40:42Z,El Jadida,2.0,Neuf,1.0,https://www.avito.ma/fr/autre_secteur/appartem...
4,Bel appartement meublé situé dans une résidenc...,870000 DH,Appt meublé à vendre Rés fermée et sécurisée H24,870000.0,NaN,72 m²,2026-05-31T05:04:04Z,Casablanca,2.0,Bon état,1.0,https://www.avito.ma/fr/belv%C3%A9d%C3%A8re/ap...
...,...,...,...,...,...,...,...,...,...,...,...,...
41566,Cherche appartement ou maison 230000dh maximum,NaN,Appartement à vendre 60 m² à Salé,NaN,NaN,60 m²,2025-04-25T18:55:02Z,Salé,2.0,NaN,NaN,https://www.avito.ma/fr/hay_salam/appartements...
41567,Appartement à vendre à mohammedia 1 étage à 3 ...,540000 DH,Appartement à vendre 82 m² à Mohammedia,540000.0,NaN,82 m²,2025-04-25T17:49:01Z,Mohammedia,2.0,Bon état,1.0,https://www.avito.ma/fr/centre_ville/apparteme...
41568,Apt n 2 au 1 er étage superficie 168 m2 et 5m2...,NaN,سعيدة 1 اقامة الغروب 5,NaN,NaN,168 m²,2025-04-19T20:46:01Z,Safi,3.0,Bon état,2.0,https://www.avito.ma/fr/sa%C3%A2ida_1_et_2/app...
41569,شقة سفلية للبيع صالون وجوج غرف و مرح قريبة لنه...,NaN,Appartement à vendre 50 m² à Casablanca,NaN,NaN,50 m²,2025-04-19T18:39:01Z,Casablanca,2.0,NaN,1.0,https://www.avito.ma/fr/sidi_moumen/appartemen...
41570,Appartements neufs haut standing dans un secte...,784000 DH,Appartements neufs haut standing Dar Bouazza,784000.0,NaN,80 m²,2025-04-19T17:30:09Z,Dar Bouazza,2.0,Neuf,2.0,https://www.avito.ma/fr/dar_bouazza/appartemen...

In [9]:
df_mubwab = pd.read_csv('Silver/mubawab_listings.csv')

In [10]:
import re
from urllib.parse import unquote

# === 1. Extract dates from image_names ===
def extract_date_from_images(img_names):
    if pd.isna(img_names):
        return None
    decoded = unquote(str(img_names))
    
    patterns = [
        r'WhatsApp.*?(\d{4})-(\d{2})-(\d{2})',
        r'IMG-(\d{4})(\d{2})(\d{2})',
        r'(\d{4})(\d{2})(\d{2})_\d{6}',
        r'Generated.*?(\d{4}).*?(\d{2}).*?(\d{2})',
        r'(\d{4})(\d{2})(\d{2})',
    ]
    
    for pat in patterns:
        m = re.search(pat, decoded, re.IGNORECASE)
        if m:
            try:
                groups = m.groups()
                if len(groups) == 3:
                    y, mth, d = map(int, groups)
                    if 2015 <= y <= 2027 and 1 <= mth <= 12 and 1 <= d <= 31:
                        return f"{y:04d}-{mth:02d}-{d:02d}"
            except:
                continue
    return None

df_mubwab['extracted_date'] = df_mubwab['image_names'].apply(extract_date_from_images)
df_mubwab['listing_date'] = pd.to_datetime(df_mubwab['extracted_date'], errors='coerce')

# === 2. Fill missing dates using ad_id ===
df_mubwab['ad_id_num'] = pd.to_numeric(df_mubwab['ad_id'], errors='coerce')
df_mubwab = df_mubwab.sort_values('ad_id_num').reset_index(drop=True)

df_mubwab['listing_date_filled'] = df_mubwab['listing_date'].copy()
df_mubwab['listing_date_filled'] = df_mubwab['listing_date_filled'].interpolate(
    method='linear', 
    limit_direction='both'
)

# Final date
df_mubwab['listing_date'] = df_mubwab['listing_date'].combine_first(df_mubwab['listing_date_filled'])

# === NEW: Boolean column ===
df_mubwab['is_extracted'] = df_mubwab['listing_date'].notna()

In [11]:
split = df_mubwab['location'].str.split(r'\s*,+\s*', n=1, expand=True, regex=True)

df_mubwab['area'] = split[0].str.strip()
df_mubwab['city'] = split[1].str.strip()

In [12]:
### MUBWAB RAW DATA
df_mubwab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16658 entries, 0 to 16657
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title                16658 non-null  object
 1   price_DH             15103 non-null  object
 2   location             16658 non-null  object
 3   surface_m2           16096 non-null  float64
 4   rooms                14130 non-null  float64
 5   bedrooms             16018 non-null  float64
 6   bathrooms            6015 non-null   float64
 7   ad_id                16658 non-null  int64
 8   listing_type         7004 non-null   object
 9   condition            5922 non-null   object
 10  orientation          2453 non-null   object
 11  floor_type           3319 non-null   object
 12  garden_m2            58 non-null     float64
 13  garage_spaces        162 non-null    float64
 14  features_text        15479 non-null  object
 15  phone                0 non-null      float64
 16  agency_name          5871 non-null   object
 17  agency_url           5871 non-null   object
 18  image_names          15639 non-null  object
 19  description          7458 non-null   object
 20  url                  16658 non-null  object
 21  page                 16658 non-null  int64
 22  extracted_date       4998 non-null   object
 23  listing_date         16658 non-null  datetime64[ns]
 24  ad_id_num            16658 non-null  int64
 25  listing_date_filled  16658 non-null  datetime64[ns]
 26  is_extracted         16658 non-null  bool
 27  area                 16658 non-null  object
 28  city                 16539 non-null  object
dtypes: bool(1), datetime64[ns](2), float64(7), int64(3), object(16)
memory usage: 3.6+ MB

In [13]:
df_mubwab = df_mubwab.drop(
    columns=[
        'location', 'ad_id', 'listing_type', 'orientation', 'floor_type',
        'garden_m2', 'garage_spaces', 'features_text', 'phone',
        'agency_name', 'agency_url', 'image_names', 'page', 'extracted_date',
        'listing_date', 'ad_id_num', 'is_extracted'
        
    ]
)

In [14]:
df_mubwab['price_DH'].rename('')
df_mubwab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16658 entries, 0 to 16657
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title                16658 non-null  object
 1   price_DH             15103 non-null  object
 2   surface_m2           16096 non-null  float64
 3   rooms                14130 non-null  float64
 4   bedrooms             16018 non-null  float64
 5   bathrooms            6015 non-null   float64
 6   condition            5922 non-null   object
 7   description          7458 non-null   object
 8   url                  16658 non-null  object
 9   listing_date_filled  16658 non-null  datetime64[ns]
 10  area                 16658 non-null  object
 11  city                 16539 non-null  object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 1.5+ MB

In [ ]:
df_mubwab.count()

NameError: name 'null' is not defined

In [16]:
df_mubwab.sample(10)

,title,price_DH,surface_m2,rooms,bedrooms,bathrooms,condition,description,url,listing_date_filled,area,city
7788,Appartement mansouria,850 000 DH,63.0,1.0,1.0,1.0,NaN,NaN,https://www.mubawab.ma/fr/a/8230782/appartemen...,2025-10-03 13:30:00,El Mansouria,El Mansouria
15444,"Appartement à vendre 75 m², 2 chambres Autre S...",1 650 000 DH,75.0,NaN,2.0,NaN,NaN,Découvrez cet appartement lumineux et bien age...,https://www.mubawab.ma/fr/a/8330886/appartemen...,2026-04-09 00:00:00,Temara,Temara
9961,"Appartement à vendre 72 m², 2 chambres Sidi Ma...",700 000 DH,72.0,NaN,2.0,1.0,NaN,NaN,https://www.mubawab.ma/fr/a/8262458/appartemen...,2025-06-12 00:00:00,Sidi Maarouf,Casablanca
6795,Bel appartement spacieux de 159 m²,2 400 000 DH,159.0,5.0,2.0,NaN,NaN,NaN,https://www.mubawab.ma/fr/a/8211379/bel-appart...,2025-08-31 00:00:00,Les princesses,Casablanca
13060,Appartement 214m²,NaN,214.0,4.0,3.0,NaN,NaN,NaN,https://www.mubawab.ma/fr/a/8304731/appartemen...,2026-02-14 00:00:00,Route ain Chkaf,Fès
11185,Appartement à vendre 127 m² Quart. Les Princesses,2 100 000 DH,127.0,4.0,3.0,NaN,NaN,NaN,https://www.mubawab.ma/fr/a/8277985/appartemen...,2021-04-29 00:00:00,Les princesses,Casablanca
6848,Vente appartement haut standind a un prix bas,1 330 000 DH,105.0,2.0,3.0,NaN,NaN,NaN,https://www.mubawab.ma/fr/a/8212375/vente-appa...,2025-09-11 00:00:00,Belvédère,Casablanca
10413,Asilah beralmar projet touristique appartement...,2 250 000 DH,125.0,1.0,3.0,NaN,Bon état / habitable,"Il s’agit d’un appartement première main, en e...",https://www.mubawab.ma/fr/a/8266934/asilah-ber...,2025-12-05 00:00:00,Asilah,Asilah
13239,Appartement a vendre Prestigia saphir,2 250 000 DH,76.0,5.0,2.0,1.0,Bon état / habitable,Turnkay vous proposes un appartement à vendre ...,https://www.mubawab.ma/fr/a/8306521/appartemen...,2026-02-25 00:00:00,Boulevard Med 6,Marrakech
16422,Apartment rond point Ajanif,910 000 DH,120.0,3.0,3.0,1.0,Bon état / habitable,Apartment rond point Ajanif 3em étage 3 façade...,https://www.mubawab.ma/fr/a/8339839/apartment-...,2026-04-15 00:00:00,Wilaya,Tétouan